Try @kabalin way for CI
- [skip ci]

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,7 +1,12 @@
-name: Run all tests
+name: Moodle Plugin CI
 
-# Run this workflow every time a new commit pushed to your repository
-on: push
+on:
+  push:
+    branches:
+      - 'master'
+  pull_request:
+    branches:
+      - 'master'
 
 jobs:
   moodle-310:
@@ -10,77 +15,93 @@ jobs:
 
     env:
       MOODLE_BRANCH: MOODLE_310_STABLE
-      DB: pgsql
-      CHECK_GRUNT: no
-      CHECK_BEHAT: no
 
     services:
       postgres:
-        image: postgres
+        image: postgres:9.6
         env:
           POSTGRES_USER: moodleuser
           POSTGRES_PASSWORD: moodle
+        ports:
+          - 5432:5432
         options: >-
           --health-cmd pg_isready
           --health-interval 10s
           --health-timeout 5s
-          --health-retries 5
+          --health-retries 3
+      mariadb:
+        image: mariadb:10
+        env:
+          MYSQL_USER: 'root'
+          MYSQL_ALLOW_EMPTY_PASSWORD: "true"
         ports:
-          - 5432:5432
+        - 3306:3306
+        options: >-
+          --health-cmd="mysqladmin ping"
+          --health-interval 10s
+          --health-timeout 5s
+          --health-retries 3
+
+    strategy:
+      fail-fast: false
+      matrix:
+        php-versions:
+          - '7.3'
+          - '7.4'
+        database:
+          - 'pgsql'
+          - 'mariadb'
 
     steps:
-      - name: Create required locale
-        run: sudo locale-gen en_AU.UTF-8
+    - name: Check out repository code
+      uses: actions/checkout@v2
+      with:
+        # Clone in plugin subdir, so we can setup CI in default directory.
+        path: plugin
 
-      - name: Checkout
-        uses: actions/checkout@v2
-        with:
-          path: this-plugin
+    - name: Install node
+      uses: actions/setup-node@v1
+      with:
+        # TODO: Check if we can support .nvmrc
+        node-version: '14.15.0'
 
-      - name: Checkout my custom moodle-plugin-ci
-        uses: actions/checkout@v2
-        with:
-          repository: timhunt/moodle-plugin-ci
-          path: ci
+    - name: Setup PHP environment
+      uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
+      with:
+        php-version: ${{ matrix.php-versions }}
+        extensions: mbstring, pgsql
+        tools: phpunit
 
-      - name: Composer install
-        run: cd ci; composer install
+    - name: Deploy moodle-plugin-ci
+      run: |
+        composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^3
+        # Add dirs to $PATH
+        echo $(cd ci/bin; pwd) >> $GITHUB_PATH
+        echo $(cd ci/vendor/bin; pwd) >> $GITHUB_PATH
+        # PHPUnit depends on en_AU.UTF-8 locale
+        sudo locale-gen en_AU.UTF-8
 
-      - name: Set path 1
-        run: echo "$(cd ci/bin; pwd)" >> $GITHUB_PATH
+    - name: Install moodle-plugin-ci
+      # Need explicit IP to stop mysql client using domain socket.
+      run: moodle-plugin-ci install -vvv --plugin ./plugin --db-host=127.0.0.1
+      env:
+        DB: ${{ matrix.database }}
+        # TODO: Omitted MOODLE_BRANCH results in regex failure, investigate.
+        MOODLE_BRANCH: ${{ MOODLE_BRANCH }}
 
-      - name: Set path 2
-        run: echo "$(cd ci/vendor/bin; pwd)" >> $GITHUB_PATH
-
-      - name: Install Moodle
-        run: moodle-plugin-ci install --db-user moodleuser --db-pass moodle --plugin this-plugin
-
-      - name: phplint
-        run: moodle-plugin-ci phplint
-
-      - name: phpcpd
-        run: moodle-plugin-ci phpcpd || true
-
-      - name: phpmd
-        run: moodle-plugin-ci phpmd
-
-      - name: codechecker
-        run: moodle-plugin-ci codechecker
-
-      - name: validate
-        run: moodle-plugin-ci validate
-
-      - name: savepoints
-        run: moodle-plugin-ci savepoints
-
-      - name: mustache
-        run: moodle-plugin-ci mustache
-
-      - name: grunt
-        run: moodle-plugin-ci grunt || [ "$CHECK_GRUNT" = 'no' ]
-
-      - name: phpunit
-        run: moodle-plugin-ci phpunit
-
-      - name: behat
-        run: moodle-plugin-ci behat --profile chrome || [ "$CHECK_BEHAT" = 'no' ]
+    - name: Run Integration tests
+      run: |
+        # Currently it stops if any command return non 0 exist status, need
+        # wrapper to collect exist status and list result and the end.
+        # For testing purposes at this stage, just assume each command succeeds.
+        moodle-plugin-ci phplint || true
+        moodle-plugin-ci phpcpd || true
+        moodle-plugin-ci phpmd || true
+        moodle-plugin-ci codechecker || true
+        moodle-plugin-ci validate || true
+        moodle-plugin-ci savepoints || true
+        moodle-plugin-ci mustache || true
+        moodle-plugin-ci grunt || true
+        moodle-plugin-ci phpdoc || true
+        moodle-plugin-ci phpunit || true
+        moodle-plugin-ci behat || true
