Update CI

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -9,12 +9,9 @@ on:
       - 'master'
 
 jobs:
-  moodle-310:
+  test:
     name: With Moodle 3.10
     runs-on: ubuntu-latest
-
-    env:
-      MOODLE_BRANCH: MOODLE_310_STABLE
 
     services:
       postgres:
@@ -45,9 +42,11 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        php-versions:
+        php:
           - '7.3'
           - '7.4'
+        moodle-branch:
+          - 'MOODLE_310_STABLE'
         database:
           - 'pgsql'
           - 'mariadb'
@@ -59,20 +58,21 @@ jobs:
         # Clone in plugin subdir, so we can setup CI in default directory.
         path: plugin
 
-    - name: Install node
-      uses: actions/setup-node@v1
-      with:
-        # TODO: Check if we can support .nvmrc
-        node-version: '14.15.0'
+#     - name: Install node
+#       uses: actions/setup-node@v1
+#       with:
+#         # TODO: Check if we can support .nvmrc
+#         node-version: '14.15.0'
 
     - name: Setup PHP environment
-      uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
+      uses: shivammathur/setup-php@v2
       with:
-        php-version: ${{ matrix.php-versions }}
-        extensions: mbstring, pgsql
-        tools: phpunit
+        php-version: ${{ matrix.php }}
+        coverage: none
+#         extensions: mbstring, pgsql
+#         tools: phpunit
 
-    - name: Deploy moodle-plugin-ci
+    - name: Initialise moodle-plugin-ci
       run: |
         composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^3
         # Add dirs to $PATH
@@ -80,28 +80,62 @@ jobs:
         echo $(cd ci/vendor/bin; pwd) >> $GITHUB_PATH
         # PHPUnit depends on en_AU.UTF-8 locale
         sudo locale-gen en_AU.UTF-8
+        # Allow node version switching
+        echo "NVM_DIR=$HOME/.nvm" >> $GITHUB_ENV
 
     - name: Install moodle-plugin-ci
       # Need explicit IP to stop mysql client using domain socket.
-      run: moodle-plugin-ci install -vvv --plugin ./plugin --db-host=127.0.0.1
+      run: |
+        moodle-plugin-ci install --plugin ./plugin --db-host=127.0.0.1
       env:
         DB: ${{ matrix.database }}
-        # TODO: Omitted MOODLE_BRANCH results in regex failure, investigate.
-        MOODLE_BRANCH: ${{ env.MOODLE_BRANCH }}
+        MOODLE_BRANCH: ${{ matrix.moodle-branch }}
 
-    - name: Run Integration tests
-      run: |
-        # Currently it stops if any command return non 0 exist status, need
-        # wrapper to collect exist status and list result and the end.
-        # For testing purposes at this stage, just assume each command succeeds.
-        moodle-plugin-ci phplint || true
-        moodle-plugin-ci phpcpd || true
-        moodle-plugin-ci phpmd || true
-        moodle-plugin-ci codechecker || true
-        moodle-plugin-ci validate || true
-        moodle-plugin-ci savepoints || true
-        moodle-plugin-ci mustache || true
-        moodle-plugin-ci grunt || true
-        moodle-plugin-ci phpdoc || true
-        moodle-plugin-ci phpunit || true
-        moodle-plugin-ci behat || true
+    # Currently it stops if any command return non 0 exist status, need
+    # wrapper to collect exist status and list result and the end.
+    # For testing purposes at this stage, just assume each command succeeds.
+    - name: PHP Lint
+      if: ${{ always() }}
+      run: moodle-plugin-ci phplint || true
+
+    - name: PHP Copy/Paste Detector
+      continue-on-error: true # This step will show errors but will not fail
+      if: ${{ always() }}
+      run: moodle-plugin-ci phpcpd || true
+
+    - name: PHP Mess Detector
+      continue-on-error: true # This step will show errors but will not fail
+      if: ${{ always() }}
+      run: moodle-plugin-ci phpmd || true
+
+    - name: Moodle Code Checker
+      if: ${{ always() }}
+      run: moodle-plugin-ci codechecker --max-warnings 0 || true
+
+    - name: Moodle PHPDoc Checker
+      if: ${{ always() }}
+      run: moodle-plugin-ci phpdoc || true
+
+    - name: Validating
+      if: ${{ always() }}
+      run: moodle-plugin-ci validate || true
+
+    - name: Check upgrade savepoints
+      if: ${{ always() }}
+      run: moodle-plugin-ci savepoints || true
+
+    - name: Mustache Lint
+      if: ${{ always() }}
+      run: moodle-plugin-ci mustache || true
+
+    - name: Grunt
+      if: ${{ always() }}
+      run: moodle-plugin-ci grunt --max-lint-warnings 0 || true
+
+    - name: PHPUnit tests
+      if: ${{ always() }}
+      run: moodle-plugin-ci phpunit || true
+
+    - name: Behat features
+      if: ${{ always() }}
+      run: moodle-plugin-ci behat --profile chrome || true
