Update CI workflow

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,4 +1,5 @@
 name: Moodle Plugin CI
+# Based on version gha.dist.yml version 4.1.2
 
 on:
   push:
@@ -10,7 +11,6 @@ on:
 
 jobs:
   test:
-    name: CI
     runs-on: ubuntu-22.04
 
     services:
@@ -21,11 +21,8 @@ jobs:
           POSTGRES_HOST_AUTH_METHOD: 'trust'
         ports:
           - 5432:5432
-        options: >-
-          --health-cmd pg_isready
-          --health-interval 10s
-          --health-timeout 5s
-          --health-retries 3
+        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3
+
       mariadb:
         image: mariadb:10
         env:
@@ -35,105 +32,89 @@ jobs:
           MYSQL_COLLATION_SERVER: "utf8mb4_unicode_ci"
         ports:
           - 3306:3306
-        options: >-
-          --health-cmd="mysqladmin ping"
-          --health-interval 10s
-          --health-timeout 5s
-          --health-retries 3
+        options: --health-cmd="mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 3
 
     strategy:
       fail-fast: false
       matrix:
-        php:
-          - '8.0'
-          - '8.1'
-        moodle-branch:
-          - 'MOODLE_401_STABLE'
-        database:
-          - 'pgsql'
-          - 'mariadb'
+        php: ['7.4', '8.0', '8.1']
+        moodle-branch: ['MOODLE_401_STABLE']
+        database: [pgsql, mariadb]
 
     steps:
-    - name: Check out repository code
-      uses: actions/checkout@v3
-      with:
-        # Clone in plugin subdir, so we can setup CI in default directory.
-        path: plugin
+      - name: Check out repository code
+        uses: actions/checkout@v3
+        with:
+          path: plugin
 
-    - name: Setup PHP ${{ matrix.php }}
-      uses: shivammathur/setup-php@v2
-      with:
-        php-version: ${{ matrix.php }}
-        extensions: ${{ matrix.extensions }}
-        ini-values: max_input_vars=5000
+      - name: Setup PHP ${{ matrix.php }}
+        uses: shivammathur/setup-php@v2
+        with:
+          php-version: ${{ matrix.php }}
+          extensions: ${{ matrix.extensions }}
+          ini-values: max_input_vars=5000
           # If you are not using code coverage, keep "none". Otherwise, use "pcov" (Moodle 3.10 and up) or "xdebug".
           # If you try to use code coverage with "none", it will fallback to phpdbg (which has known problems).
-        coverage: none
+          coverage: none
 
-    - name: Initialise moodle-plugin-ci
-      run: |
-        composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^4
-        # Add dirs to $PATH
-        echo $(cd ci/bin; pwd) >> $GITHUB_PATH
-        echo $(cd ci/vendor/bin; pwd) >> $GITHUB_PATH
-        # PHPUnit depends on en_AU.UTF-8 locale
-        sudo locale-gen en_AU.UTF-8
-        # Allow node version switching
-        echo "NVM_DIR=$HOME/.nvm" >> $GITHUB_ENV
+      - name: Initialise moodle-plugin-ci
+        run: |
+          composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^4
+          echo $(cd ci/bin; pwd) >> $GITHUB_PATH
+          echo $(cd ci/vendor/bin; pwd) >> $GITHUB_PATH
+          sudo locale-gen en_AU.UTF-8
+          echo "NVM_DIR=$HOME/.nvm" >> $GITHUB_ENV
 
-    - name: Install moodle-plugin-ci
-      # Need explicit IP to stop mysql client using domain socket.
-      run: |
-        moodle-plugin-ci install --plugin ./plugin --db-host=127.0.0.1
-      env:
-        DB: ${{ matrix.database }}
-        MOODLE_BRANCH: ${{ matrix.moodle-branch }}
+      - name: Install moodle-plugin-ci
+        run: |
+          moodle-plugin-ci install --plugin ./plugin --db-host=127.0.0.1
+        env:
+          DB: ${{ matrix.database }}
+          MOODLE_BRANCH: ${{ matrix.moodle-branch }}
 
-    # Currently it stops if any command return non 0 exist status, need
-    # wrapper to collect exist status and list result and the end.
-    # For testing purposes at this stage, just assume each command succeeds.
-    - name: PHP Lint
-      if: ${{ always() }}
-      run: moodle-plugin-ci phplint || true
+      # For testing purposes at this stage, just assume each command succeeds.
+      - name: PHP Lint
+        if: ${{ always() }}
+        run: moodle-plugin-ci phplint || true
 
-    - name: PHP Copy/Paste Detector
-      continue-on-error: true # This step will show errors but will not fail
-      if: ${{ always() }}
-      run: moodle-plugin-ci phpcpd || true
+      - name: PHP Copy/Paste Detector
+        continue-on-error: true # This step will show errors but will not fail
+        if: ${{ always() }}
+        run: moodle-plugin-ci phpcpd || true
 
-    - name: PHP Mess Detector
-      continue-on-error: true # This step will show errors but will not fail
-      if: ${{ always() }}
-      run: moodle-plugin-ci phpmd || true
+      - name: PHP Mess Detector
+        continue-on-error: true # This step will show errors but will not fail
+        if: ${{ always() }}
+        run: moodle-plugin-ci phpmd || true
 
-    - name: Moodle Code Checker
-      if: ${{ always() }}
-      run: moodle-plugin-ci phpcs --max-warnings 0 || true
+      - name: Moodle Code Checker
+        if: ${{ always() }}
+        run: moodle-plugin-ci phpcs --max-warnings 0 || true
 
-    - name: Moodle PHPDoc Checker
-      if: ${{ always() }}
-      run: moodle-plugin-ci phpdoc --max-warnings 0 || true
+      - name: Moodle PHPDoc Checker
+        if: ${{ always() }}
+        run: moodle-plugin-ci phpdoc --max-warnings 0 || true
 
-    - name: Validating
-      if: ${{ always() }}
-      run: moodle-plugin-ci validate || true
+      - name: Validating
+        if: ${{ always() }}
+        run: moodle-plugin-ci validate || true
 
-    - name: Check upgrade savepoints
-      if: ${{ always() }}
-      run: moodle-plugin-ci savepoints || true
+      - name: Check upgrade savepoints
+        if: ${{ always() }}
+        run: moodle-plugin-ci savepoints || true
 
-    - name: Mustache Lint
-      if: ${{ always() }}
-      run: moodle-plugin-ci mustache || true
+      - name: Mustache Lint
+        if: ${{ always() }}
+        run: moodle-plugin-ci mustache || true
 
-    - name: Grunt
-      if: ${{ always() }}
-      run: moodle-plugin-ci grunt --max-lint-warnings 0 || true
+      - name: Grunt
+        if: ${{ always() }}
+        run: moodle-plugin-ci grunt --max-lint-warnings 0 || true
 
-    - name: PHPUnit tests
-      if: ${{ always() }}
-      run: moodle-plugin-ci phpunit --fail-on-warning || true
+      - name: PHPUnit tests
+        if: ${{ always() }}
+        run: moodle-plugin-ci phpunit --fail-on-warning || true
 
-    - name: Behat features
-      if: ${{ always() }}
-      run: moodle-plugin-ci behat --profile chrome || true
+      - name: Behat features
+        if: ${{ always() }}
+        run: moodle-plugin-ci behat --profile chrome || true
